---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    # For testing in containers, a loopback device is created in `prepare.yml`.
    # The device created in `prepare.yml` is picked up here.
    # Normally you would point to /dev/sd*.
    - name: Read loop device from disk
      ansible.builtin.slurp:
        src: /loopback-devicename.txt
      register: loopback_devicename

  roles:
    - role: ansible-role-storage
      # Partitioning a loopback device is not supported by parted.
      # storage_partitions:
      #   - name: "{{ loopback_devicename.content | b64decode }}"
      #     number: 1
      #     part_end: 100%
      #     label: gpt
      storage_volumegroups:
        - name: data
          devices:
            - "{{ loopback_devicename.content | b64decode }}"
          size: 4
      storage_volumes:
        - name: test1
          vg: data
          size: 1G
          opts: --zero n
      storage_filesystems:
        - name: /dev/data/test1
          filesystem: xfs
# This causes an issue with the loopback device.
#       storage_mounts:
#         - name: /mnt/test
#           src: /dev/data/test1
#           fstype: xfs
#           owner: root
#           group: root
#           mode: "0755"
